### ISSUE TITLE
Pin?

### ISSUE THREAD

**Issue by slaveboy2000** [techman83/esp8266-wavplay#3]
What pins should I hook my speaker to so that they play my wave file? I looked through all the files and could not find it.

**Comment by techman83** [comment]
You should checkout the project [readme](https://github.com/techman83/esp8266-wavplay/blob/master/README.md) as this library isn't maintained anymore. I did do a write up on it [here](https://www.techman83.me/hardware/2017/06/04/dont_underestimate_the_doorbell.html) on how I used this one though.
